<?php
declare(strict_types=1);
function h(mixed $value): string { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); }
function svg(string $name): string {
    $icons = [
        'arrow' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-5-5 5 5-5 5"/></svg>',
        'diagonal' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 17 17 7M9 7h8v8"/></svg>',
        'certificate' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 2 2.1 2.8-.2.8 2.7 2.4 1.5-1 2.6 1 2.6-2.4 1.5-.8 2.7-2.8-.2L12 21l-2-2.1-2.8.2-.8-2.7L4 14.9l1-2.6-1-2.6 2.4-1.5.8-2.7 2.8.2L12 3Z"/><path d="m9 12 2 2 4-4"/></svg>',
        'bag' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4h10l2 16H5L7 4Z"/><path d="M9 8h6"/></svg>',
        'map' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 18-5 2V6l5-2 6 2 5-2v14l-5 2-6-2Z"/><path d="M9 4v14m6-12v14"/></svg>',
        'shield' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 5 6v5c0 4.7 2.8 8 7 10 4.2-2 7-5.3 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></svg>',
        'trace' => '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="M12 3v3m0 12v3M3 12h3m12 0h3M5.6 5.6l2.1 2.1m8.6 8.6 2.1 2.1m0-12.8-2.1 2.1m-8.6 8.6-2.1 2.1"/></svg>',
        'pin' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>',
        'mail' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v14H4z"/><path d="m4 7 8 6 8-6"/></svg>',
        'phone' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3 4 5c0 8 7 15 15 15l2-3-4-3-2 2c-3-1-6-4-7-7l2-2-3-4Z"/></svg>',
        'instagram' => '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/></svg>',
        'facebook' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 21v-8h3l.5-3H14V8.5c0-1 .5-1.5 1.8-1.5H18V4.2c-.7-.1-1.6-.2-2.8-.2-2.8 0-4.7 1.7-4.7 4.8V10H8v3h2.5v8"/></svg>',
        'whatsapp' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 11.5a8 8 0 0 1-11.7 7L4 20l1.5-4.1A8 8 0 1 1 20 11.5Z"/><path d="M9 8.5c.5 2.7 2.2 4.4 5 5l1-1"/></svg>',
        'play' => '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 6 9 6-9 6V6Z"/></svg>',
        'globe' => '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c2.4 2.5 3.7 5.5 3.7 9S14.4 18.5 12 21c-2.4-2.5-3.7-5.5-3.7-9S9.6 5.5 12 3Z"/></svg>'
    ];
    return $icons[$name] ?? '';
}
try {
    $config = require __DIR__.'/cms-config/database.php';
    $db = new PDO(sprintf('mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4',$config['host'],$config['port'],$config['database']),$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
} catch (Throwable) { http_response_code(503); exit('Contenido temporalmente no disponible.'); }

$lang = ($_GET['lang'] ?? 'es') === 'en' ? 'en' : 'es';
$slug = trim((string)($_GET['slug'] ?? ''));
$lineAlias = (string)($_GET['line'] ?? '');
$line = in_array($lineAlias,['retail','linea-retail','retail-line'],true) ? 'retail' : 'conventional';
$query = $db->prepare("SELECT p.id,p.image_path,l.slug line_slug,c.name_es category_es,c.name_en category_en,t.name,t.slug,t.short_description,t.description,t.seo_title,t.seo_description,COALESCE(sp.scientific_name,'') scientific_name,COALESCE(sp.tariff_code,'') tariff_code,COALESCE(IF(?='es',sp.caliber_es,sp.caliber_en),'') caliber,COALESCE(IF(?='es',sp.destinations_es,sp.destinations_en),'') destinations,COALESCE(sp.technical_sheet_path,'') technical_sheet_path FROM products p JOIN product_lines l ON l.id=p.line_id JOIN product_categories c ON c.id=p.category_id JOIN product_translations t ON t.product_id=p.id AND t.locale=? LEFT JOIN product_specs sp ON sp.product_id=p.id WHERE t.slug=? AND l.slug=? AND p.is_active=1 AND p.deleted_at IS NULL LIMIT 1");
$query->execute([$lang,$lang,$lang,$slug,$line]); $product = $query->fetch();
if (!$product) {
    http_response_code(404); $message=$lang==='es'?'Producto no encontrado':'Product not found';
    ?><!doctype html><html lang="<?=$lang?>"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($message)?></title><link rel="stylesheet" href="/product-detail.css"><main class="not-found"><img src="/images/logo.webp" alt="Royal Beans Perú"><h1><?=h($message)?></h1><a href="<?=$lang==='es'?'/productos/':'/en/products/'?>"><?=$lang==='es'?'Volver a productos':'Back to products'?></a></main></html><?php exit;
}
$category=$lang==='es'?$product['category_es']:$product['category_en'];
$galleryQuery=$db->prepare('SELECT * FROM product_gallery WHERE product_id=? ORDER BY sort_order,id');$galleryQuery->execute([$product['id']]);$gallery=$galleryQuery->fetchAll();array_unshift($gallery,['media_type'=>'image','media_path'=>$product['image_path'],'alt_es'=>$product['name'],'alt_en'=>$product['name']]);
$q=$db->prepare('SELECT * FROM product_packages WHERE product_id=? ORDER BY sort_order,id');$q->execute([$product['id']]);$packages=$q->fetchAll();
if(!$packages){$packages=[['weight_primary'=>'25 kg','weight_secondary'=>'50 lb','material_es'=>'Polipropileno','material_en'=>'Polypropylene','package_type'=>'sack'],['weight_primary'=>'50 kg','weight_secondary'=>'100 lb','material_es'=>'Polipropileno','material_en'=>'Polypropylene','package_type'=>'sack'],['weight_primary'=>'Big Bag','weight_secondary'=>'','material_es'=>'Capacidad bajo consulta','material_en'=>'Capacity upon request','package_type'=>'big-bag']];}
$q=$db->prepare('SELECT month_number,availability FROM product_harvest WHERE product_id=?');$q->execute([$product['id']]);$harvest=array_column($q->fetchAll(),'availability','month_number');
$q=$db->prepare('SELECT name FROM product_certifications WHERE product_id=? ORDER BY sort_order,id');$q->execute([$product['id']]);$certifications=array_column($q->fetchAll(),'name');
$q=$db->prepare("SELECT p.id,p.image_path,t.name,t.slug,c.name_es,c.name_en FROM product_relations r JOIN products p ON p.id=r.related_product_id JOIN product_translations t ON t.product_id=p.id AND t.locale=? JOIN product_categories c ON c.id=p.category_id WHERE r.product_id=? AND p.is_active=1 AND p.deleted_at IS NULL ORDER BY r.sort_order LIMIT 4");$q->execute([$lang,$product['id']]);$related=$q->fetchAll();
if(count($related)<4){$ids=array_merge([(int)$product['id']],array_map(fn($item)=>(int)$item['id'],$related));$marks=implode(',',array_fill(0,count($ids),'?'));$q=$db->prepare("SELECT p.id,p.image_path,t.name,t.slug,c.name_es,c.name_en FROM products p JOIN product_translations t ON t.product_id=p.id AND t.locale=? JOIN product_categories c ON c.id=p.category_id JOIN product_lines l ON l.id=p.line_id WHERE l.slug=? AND p.id NOT IN ($marks) AND p.is_active=1 AND p.deleted_at IS NULL ORDER BY p.sort_order LIMIT ?");$args=[$lang,$line,...$ids,4-count($related)];foreach($args as $index=>$value)$q->bindValue($index+1,$value,is_int($value)?PDO::PARAM_INT:PDO::PARAM_STR);$q->execute();$related=array_merge($related,$q->fetchAll());}
$settings=[];foreach($db->query('SELECT setting_key,value_text FROM settings WHERE is_public=1') as $item)$settings[$item['setting_key']]=$item['value_text'];
$email=$settings['company_email']??'administracion@royalbeansperu.com';$phone=$settings['company_phone']??'+51 961 804 500';$whatsapp=$settings['whatsapp']??'51961804500';$instagram=$settings['instagram']??'https://www.instagram.com/royalbeans_peru/';$facebook=$settings['facebook']??'https://www.facebook.com/profile.php?id=61573866174999';$address=$lang==='es'?($settings['address_es']??'Chiclayo, Lambayeque, Perú'):($settings['address_en']??'Chiclayo, Lambayeque, Peru');
$months=$lang==='es'?['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
$base=$lang==='es'?'/productos/'.($line==='retail'?'linea-retail':'linea-convencional').'/':'/en/products/'.($line==='retail'?'retail-line':'conventional-line').'/';$contact=$lang==='es'?'/contacto/':'/en/contact/';$title=$product['seo_title']?:$product['name'].' | Royal Beans Perú';$description=$product['seo_description']?:$product['short_description'];$consult=$lang==='es'?'Consultar con nuestro equipo':'Ask our team';
$nav=$lang==='es'?[['Inicio','/'],['Nosotros','/nosotros/'],['Productos','/productos/'],['Participación','/participacion/'],['Presencia','/presencia/'],['Impacto','/impacto/']]:[['Home','/en/'],['About us','/en/about-us/'],['Products','/en/products/'],['Events','/en/events/'],['Presence','/en/presence/'],['Impact','/en/impact/']];
$origin=str_contains(mb_strtolower($product['name']),'loctao')?($lang==='es'?'Chepén — Perú':'Chepén — Peru'):($lang==='es'?'Perú':'Peru');$presentation=implode(' / ',array_slice(array_column($packages,'weight_primary'),0,3));$publishedText=$product['description']?:($lang==='es'?'Royal Beans Perú comercializa este producto seleccionado para atender requerimientos comerciales y mercados internacionales.':'Royal Beans Peru supplies this selected product for commercial requirements and international markets.');
?><!doctype html><html lang="<?=$lang?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h($title)?></title><meta name="description" content="<?=h($description)?>"><link rel="stylesheet" href="/product-detail.css"><link rel="stylesheet" href="/product-detail-complete.css"><script type="application/ld+json"><?=json_encode(['@context'=>'https://schema.org','@type'=>'Product','name'=>$product['name'],'image'=>[$product['image_path']],'description'=>$description,'brand'=>['@type'=>'Brand','name'=>'Royal Beans Perú']],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)?></script></head><body>
<header class="pd-header"><a class="pd-brand" href="<?=$lang==='es'?'/':'/en/'?>" aria-label="Royal Beans Perú"><span class="pd-brand-mark"><img src="/images/logo.webp" alt=""></span><span class="pd-brand-copy"><strong>ROYAL BEANS</strong><small>- PERÚ -</small></span></a><nav class="pd-desktop-nav" aria-label="<?=$lang==='es'?'Navegación principal':'Main navigation'?>"><?php foreach($nav as [$label,$url]):$current=str_contains($url,'productos')||str_contains($url,'products');?><a class="pd-nav-item<?=$current?' active':''?>" <?=$current?'aria-current="page"':''?> href="<?=$url?>"><span><?=h($label)?></span></a><?php endforeach;?><a class="pd-nav-item contact-link" href="<?=$contact?>"><span><?=$lang==='es'?'Contáctanos':'Contact us'?></span></a></nav><div class="pd-actions"><?=svg('globe')?><div class="pd-languages"><a href="<?=$lang==='es'?'#':'/'?>" <?=$lang==='es'?'aria-current="page"':''?>>ES</a><span>/</span><a href="<?=$lang==='en'?'#':'/en/products/'?>" <?=$lang==='en'?'aria-current="page"':''?>>EN</a></div><button class="pd-menu" type="button" aria-label="<?=$lang==='es'?'Abrir menú':'Open menu'?>" aria-expanded="false"><span></span><span></span><span></span></button></div></header><div class="pd-mobile-nav" hidden><?php foreach($nav as [$label,$url]):?><a href="<?=$url?>"><?=h($label)?></a><?php endforeach;?><a href="<?=$contact?>"><?=$lang==='es'?'Contáctanos':'Contact us'?></a></div>
<main data-product-id="<?=$product['id']?>"><section class="product-hero"><div class="gallery"><div class="gallery-main"><img id="main-product-image" src="<?=h($gallery[0]['media_path'])?>" alt="<?=h($product['name'])?>"></div><div class="gallery-thumbs"><?php foreach($gallery as $index=>$item):if($item['media_type']==='image'):?><button class="<?=$index===0?'active':''?>" data-image="<?=h($item['media_path'])?>" aria-label="<?=h(($lang==='es'?'Ver imagen ':'View image ').($index+1))?>"><img src="<?=h($item['media_path'])?>" alt=""></button><?php else:?><a class="video-thumb" href="<?=h($item['media_path'])?>" target="_blank" rel="noreferrer" aria-label="<?=$lang==='es'?'Ver video':'View video'?>"><?=svg('play')?></a><?php endif;endforeach;?></div></div><article class="product-copy"><a class="crumb" href="<?=h($base)?>">← <?=h($lang==='es'?'Volver a la línea de productos':'Back to product line')?></a><p class="eyebrow">· <?=h($category)?> ·</p><h1><?=h($product['name'])?></h1><p class="lead"><?=h($product['short_description']?:($lang==='es'?'Producto peruano seleccionado para operaciones comerciales y mercados internacionales.':'Selected Peruvian product for commercial operations and international markets.'))?></p><?php if($product['description']):?><p><?=nl2br(h($product['description']))?></p><?php endif;?><dl><?php foreach([[$lang==='es'?'Origen comercial':'Commercial origin',$origin],[$lang==='es'?'Presentación':'Packaging',$presentation],[$lang==='es'?'Nombre científico':'Scientific name',$product['scientific_name']],[$lang==='es'?'Partida arancelaria':'Tariff code',$product['tariff_code']],[$lang==='es'?'Calibre':'Caliber',$product['caliber']],[$lang==='es'?'Destinos principales':'Main destinations',$product['destinations']]] as [$label,$value]):?><div><dt><?=h($label)?></dt><dd class="<?=$value?'':'pending'?>"><?=h($value?:$consult)?></dd></div><?php endforeach;?></dl><div class="certs"><?php if($certifications):foreach($certifications as $certification):?><span><?=svg('certificate')?><?=h($certification)?></span><?php endforeach;else:?><span><?=svg('certificate')?><?=$lang==='es'?'Documentación según destino':'Documentation by destination'?></span><?php endif;?></div><div class="product-actions"><a class="primary" href="<?=h($contact.'?product='.rawurlencode($product['name']))?>"><?=$lang==='es'?'Solicitar cotización':'Request a quote'?><?=svg('arrow')?></a><a class="secondary" href="<?=h($product['technical_sheet_path']?:$contact.'?product='.rawurlencode($product['name']).'&request=technical-sheet')?>" <?=$product['technical_sheet_path']?'target="_blank"':''?>><?=$lang==='es'?'Ficha técnica':'Technical sheet'?><?=svg('diagonal')?></a></div></article></section>
<section class="operations-suite"><section class="pd-section package-section"><header><p class="eyebrow">· <?=$lang==='es'?'PRESENTACIONES':'PACKAGING'?> ·</p><h2><?=$lang==='es'?'Empaque disponible':'Available packaging'?></h2><p><?=$lang==='es'?'Presentaciones comerciales preparadas de acuerdo con el producto, volumen y destino.':'Commercial presentations prepared according to product, volume and destination.'?></p></header><div class="package-grid"><?php foreach($packages as $package):?><article><?=svg('bag')?><div><strong><?=h($package['weight_primary'])?></strong><?php if($package['weight_secondary']):?><span><?=h($package['weight_secondary'])?></span><?php endif;?></div><p><?=h($lang==='es'?$package['material_es']:$package['material_en'])?></p><small><?=h($package['package_type']==='big-bag'?'BIG BAG':($lang==='es'?'SACO COMERCIAL':'COMMERCIAL SACK'))?></small></article><?php endforeach;?></div></section>
<section class="pd-section harvest-section"><div class="harvest-console-head"><span><i></i><?=$lang==='es'?'CALENDARIO OPERATIVO':'OPERATING CALENDAR'?></span><strong>12 <?=$lang==='es'?'MESES':'MONTHS'?></strong></div><header><p class="eyebrow">· <?=$lang==='es'?'COSECHA Y DISPONIBILIDAD':'HARVEST & AVAILABILITY'?> ·</p><h2><?=$lang==='es'?'Planifica tu operación':'Plan your operation'?></h2><p><?=$lang==='es'?'El calendario se actualiza desde el panel administrativo para cada producto.':'The calendar is updated for every product from the administration panel.'?></p></header><div class="harvest-grid"><?php foreach($months as $index=>$month):$status=$harvest[$index+1]??'none';?><div class="<?=h($status)?>"><span class="month-name"><?=h($month)?></span><i><b></b></i><small><?=h(($lang==='es'?['harvest'=>'Cosecha','available'=>'Disponible','limited'=>'Limitado','none'=>'Por confirmar']:['harvest'=>'Harvest','available'=>'Available','limited'=>'Limited','none'=>'To confirm'])[$status]??'')?></small></div><?php endforeach;?></div><div class="legend"><span class="harvest">● <?=$lang==='es'?'Cosecha':'Harvest'?></span><span class="available">● <?=$lang==='es'?'Disponible':'Available'?></span><span class="limited">● <?=$lang==='es'?'Limitado':'Limited'?></span><span class="none">● <?=$lang==='es'?'Por confirmar':'To be confirmed'?></span></div></section></section>
<section class="pd-section faq-section"><header><p class="eyebrow">· <?=$lang==='es'?'RESOLVEMOS TUS CONSULTAS':'YOUR QUESTIONS ANSWERED'?> ·</p><h2><?=$lang==='es'?'Preguntas frecuentes':'Frequently asked questions'?></h2></header><div class="faq-list"><details><summary><?=$lang==='es'?'¿Cuál es el origen comercial de este producto?':'What is the commercial origin of this product?'?></summary><p><?=h($origin)?></p></details><details><summary><?=$lang==='es'?'¿En qué presentaciones se comercializa?':'Which packaging options are available?'?></summary><p><?=h($presentation)?></p></details><details><summary><?=$lang==='es'?'¿Cuál es su destino comercial?':'What is its commercial destination?'?></summary><p><?=h($product['destinations']?:$consult)?></p></details><details><summary><?=$lang==='es'?'¿Cómo se gestiona la trazabilidad?':'How is traceability managed?'?></summary><p><?=$lang==='es'?'El seguimiento se realiza de acuerdo con el origen, el lote y los requisitos de cada operación comercial.':'Tracking is managed according to origin, lot and the requirements of each commercial operation.'?></p></details></div></section>
<?php if($related):?><section class="pd-section related-section"><header><p class="eyebrow">· <?=$lang==='es'?'TAMBIÉN TE PUEDE INTERESAR':'YOU MAY ALSO LIKE'?> ·</p><h2><?=$lang==='es'?'Productos relacionados':'Related products'?></h2></header><div class="related-grid"><?php foreach($related as $item):?><a href="<?=h($base.$item['slug'].'/')?>"><img src="<?=h($item['image_path'])?>" alt="<?=h($item['name'])?>"><span><?=h($lang==='es'?$item['name_es']:$item['name_en'])?></span><strong><?=h($item['name'])?></strong><?=svg('diagonal')?></a><?php endforeach;?></div></section><?php endif;?>
<section class="pd-cta"><div><p class="eyebrow">· <?=$lang==='es'?'HABLEMOS DE NEGOCIOS':'LET’S TALK BUSINESS'?> ·</p><h2><?=$lang==='es'?'Llevemos este producto a nuevos mercados.':'Let’s take this product to new markets.'?></h2></div><a href="<?=h($contact.'?product='.rawurlencode($product['name']))?>"><?=$lang==='es'?'Contáctanos':'Contact us'?><?=svg('arrow')?></a></section></main>
<footer class="pd-footer"><div class="pd-footer-grid"><div class="footer-brand"><a class="pd-brand" href="<?=$lang==='es'?'/':'/en/'?>"><img src="/images/logo.webp" alt="Royal Beans Perú"><span><strong>ROYAL BEANS</strong><small>· PERÚ ·</small></span></a><p><?=$lang==='es'?'Productos peruanos para mercados que valoran el origen, la calidad y la trazabilidad.':'Peruvian products for markets that value origin, quality and traceability.'?></p></div><nav class="footer-column" aria-label="<?=$lang==='es'?'Enlaces del sitio':'Site links'?>"><h2><?=$lang==='es'?'Explora':'Explore'?></h2><?php foreach($nav as [$label,$url]):?><a href="<?=$url?>"><?=h($label)?></a><?php endforeach;?></nav><div class="footer-column"><h2><?=$lang==='es'?'Contacto':'Contact'?></h2><p><?=svg('pin')?><?=h($address)?></p><a href="mailto:<?=h($email)?>"><?=svg('mail')?><?=h($email)?></a><a href="tel:<?=h(preg_replace('/[^+0-9]/','',$phone))?>"><?=svg('phone')?><?=h($phone)?></a></div><div class="footer-column"><h2><?=$lang==='es'?'Síguenos':'Follow us'?></h2><a href="<?=h($instagram)?>" target="_blank" rel="noreferrer"><?=svg('instagram')?>Instagram</a><a href="<?=h($facebook)?>" target="_blank" rel="noreferrer"><?=svg('facebook')?>Facebook</a><a href="https://wa.me/<?=h($whatsapp)?>" target="_blank" rel="noreferrer"><?=svg('whatsapp')?>WhatsApp</a></div></div><div class="pd-footer-bottom"><span>© <?=date('Y')?> Royal Beans Perú S.A.C.</span><span><?=$lang==='es'?'Origen peruano · Alcance global':'Peruvian origin · Global reach'?></span><a href="<?=$lang==='es'?'/politica-de-privacidad/':'/en/privacy-policy/'?>"><?=$lang==='es'?'Política de privacidad':'Privacy policy'?></a></div></footer><a class="whatsapp-float" href="https://wa.me/<?=h($whatsapp)?>" target="_blank" rel="noreferrer" aria-label="WhatsApp"><?=svg('whatsapp')?></a>
<script>document.querySelectorAll('[data-image]').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#main-product-image').src=button.dataset.image;document.querySelectorAll('[data-image]').forEach(item=>item.classList.remove('active'));button.classList.add('active')}));const menu=document.querySelector('.pd-menu'),mobile=document.querySelector('.pd-mobile-nav');menu?.addEventListener('click',()=>{const open=mobile.hidden;mobile.hidden=!open;menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});</script></body></html>
