export default function PrivacyPage({ lang }: { lang: "es" | "en" }) {
  const es = lang === "es";
  return <main className="legal"><a href={es ? "/" : "/en/"}>← Royal Beans Perú</a><h1>{es ? "Privacidad y contacto" : "Privacy and contact"}</h1>
    <p>{es ? "Esta página describe cómo funciona el contacto en este sitio de Royal Beans Perú S.A.C." : "This page explains how contact works on this Royal Beans Perú S.A.C. website."}</p>
    <h2>{es ? "Los datos de tu consulta" : "Your enquiry details"}</h2><p>{es ? "El formulario utiliza el nombre, empresa, correo, país y mensaje que ingresas para preparar una consulta de WhatsApp. Los datos del formulario no se guardan en una base de datos de esta web ni se envían automáticamente a la empresa." : "The form uses the name, company, email, country and message you enter to prepare a WhatsApp enquiry. Form details are not stored in a website database or automatically sent to the company."}</p>
    <h2>{es ? "Cuando abres WhatsApp" : "When you open WhatsApp"}</h2><p>{es ? "Al pulsar «Conversar por WhatsApp», se abre ese servicio externo con el texto preparado. Puedes revisarlo antes de enviarlo. El uso de WhatsApp está sujeto a las condiciones y políticas de ese servicio." : "Selecting ‘Chat on WhatsApp’ opens that external service with your prepared text. You can review it before sending. WhatsApp use is subject to that service’s terms and policies."}</p>
    <h2>{es ? "Cookies y recursos" : "Cookies and resources"}</h2><p>{es ? "Esta versión del sitio no incorpora herramientas de publicidad ni analítica y no instala cookies propias. Las fuentes e imágenes se sirven desde el propio sitio. Los servicios externos a los que accedas mediante enlaces aplican sus propias políticas." : "This version of the website includes no advertising or analytics tools and sets no first-party cookies. Fonts and images are served by this website. External services you visit through links apply their own policies."}</p>
    <h2>{es ? "Consultas sobre tu información" : "Questions about your information"}</h2><p>{es ? "Para consultar sobre la información que compartes con la empresa o solicitar su actualización o eliminación, escribe a" : "For questions about information you share with the company, or to request an update or deletion, contact"} <a href="mailto:administracion@royalbeansperu.com">administracion@royalbeansperu.com</a>.</p>
  </main>;
}
