<?php
declare(strict_types=1);
require __DIR__ . '/_bootstrap.php';
$user=require_admin();$db=admin_db();
$pages=[
 ['Inicio','/','inicio'],['Nosotros','/nosotros/','nosotros'],['Productos','/productos/','productos'],
 ['Línea Convencional','/productos/linea-convencional/','productos-conventional'],['Línea Retail','/productos/linea-retail/','productos-retail'],
 ['Participación','/participacion/','participacion'],['Presencia','/presencia/','presencia'],['Impacto','/impacto/','impacto'],['Contacto','/contacto/','contacto'],
 ['Home · English','/en/','inicio'],['About · English','/en/about-us/','nosotros'],['Products · English','/en/products/','productos'],
];
$products=$db->query("SELECT p.id,l.slug line_slug,MAX(CASE WHEN t.locale='es' THEN t.name END) name_es,MAX(CASE WHEN t.locale='es' THEN t.slug END) slug_es,MAX(CASE WHEN t.locale='en' THEN t.name END) name_en,MAX(CASE WHEN t.locale='en' THEN t.slug END) slug_en FROM products p JOIN product_lines l ON l.id=p.line_id JOIN product_translations t ON t.product_id=p.id WHERE p.is_active=1 AND p.deleted_at IS NULL GROUP BY p.id,l.slug ORDER BY name_es")->fetchAll();
foreach($products as $product){$pages[]=['Producto · '.$product['name_es'],'/productos/'.($product['line_slug']==='retail'?'linea-retail':'linea-convencional').'/'.$product['slug_es'].'/','product-'.$product['id']];$pages[]=['Product · '.$product['name_en'],'/en/products/'.($product['line_slug']==='retail'?'retail-line':'conventional-line').'/'.$product['slug_en'].'/','product-'.$product['id']];}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Editor visual | Royal Beans Perú</title><link rel="stylesheet" href="/admin/admin.css"><style>
body{overflow:hidden}.visual-editor{height:100vh;display:grid;grid-template-rows:auto 1fr;background:#e9eef0}.editor-toolbar{display:flex;align-items:center;gap:14px;margin:8px;padding:10px 14px;border:1px solid #d2dce0;border-radius:12px;background:#fff}.editor-toolbar label{font-size:12px;font-weight:700}.editor-toolbar select{min-width:210px;padding:9px;border:1px solid #cbd6da;border-radius:8px}.device-switch{display:flex;padding:3px;border-radius:9px;background:#edf2f4}.device-switch button{padding:8px 12px;border:0;border-radius:7px;background:transparent;color:#53616a}.device-switch button.active{color:#075e53;background:#fff;box-shadow:0 2px 8px #183c4820}.editor-hint{color:#71808a;font-size:11px}.editor-toolbar>a{margin-left:auto;color:#075e53;font-size:12px;font-weight:700}.editor-workspace{min-height:0;display:grid;grid-template-columns:minmax(0,1fr) 285px;gap:12px;padding:6px 14px 14px}.preview-shell{display:flex;justify-content:center;min-width:0;overflow:auto;padding:12px;border-radius:14px;background:#dce5e8}.preview-frame{width:100%;height:100%;border:0;border-radius:10px;background:#fff;box-shadow:0 12px 35px #173a4620;transition:width .3s ease}.preview-frame.tablet{width:768px;flex:0 0 768px}.preview-frame.mobile{width:390px;flex:0 0 390px}.editor-inspector{overflow:auto;padding:22px;border:1px solid #d2dce0;border-radius:14px;background:#fff}.inspector-empty{height:100%;display:grid;place-content:center;text-align:center;color:#71808a}.inspector-empty span{width:52px;height:52px;display:grid;place-items:center;margin:0 auto 18px;border-radius:14px;color:#075e53;background:#e9f7dc;font-size:22px}.inspector-form{display:grid;gap:15px}.inspector-form[hidden]{display:none}.inspector-form h2{margin-bottom:0}.inspector-form label{display:grid;gap:6px;font-size:12px;font-weight:700}.inspector-form input,.inspector-form textarea,.inspector-form select{width:100%;padding:10px;border:1px solid #d2dce0;border-radius:7px}.inspector-form textarea{min-height:105px;resize:vertical}.inspector-form button,.product-edit-link{padding:12px;border:0;border-radius:8px;color:#052f26;background:#c6ee9b;font-weight:700;text-align:center}.save-state{min-height:20px;color:#477555;font-size:12px}.product-inspector{display:grid;gap:14px}.product-inspector[hidden]{display:none}@media(max-width:850px){.editor-workspace{grid-template-columns:1fr}.editor-inspector{position:fixed;z-index:20;right:12px;bottom:12px;width:min(330px,calc(100% - 24px));max-height:70vh}.editor-hint{display:none}}
</style></head><body><main class="visual-editor"><header class="editor-toolbar"><label for="page-picker">Página</label><select id="page-picker"><?php foreach($pages as [$label,$url,$key]):?><option value="<?=e($url)?>" data-page="<?=e($key)?>"><?=e($label)?></option><?php endforeach;?></select><div class="device-switch" aria-label="Tamaño de vista"><button class="active" data-device="monitor">Monitor</button><button data-device="tablet">Tablet</button><button data-device="mobile">Celular</button></div><span class="editor-hint">Haz clic en un texto o imagen resaltada para editarlo</span><a id="public-link" href="/" target="_blank">Vista pública ↗</a></header><section class="editor-workspace"><div class="preview-shell"><iframe id="preview" class="preview-frame" src="/?cms_preview=1" title="Vista editable"></iframe></div><aside class="editor-inspector"><div id="empty" class="inspector-empty"><div><span>✦</span><h2>Selecciona un elemento</h2><p>Los elementos editables se resaltan al pasar el cursor sobre ellos.</p></div></div><form id="field-form" class="inspector-form" hidden enctype="multipart/form-data"><p class="admin-eyebrow">Elemento seleccionado</p><h2 id="field-name">Contenido</h2><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="page_key"><input type="hidden" name="key"><input type="hidden" name="editing_lang" value="es"><label>Tipo<select name="field_type"><option value="text">Texto corto</option><option value="textarea">Texto largo</option><option value="image">Imagen</option><option value="url">Enlace</option></select></label><label>Nombre en el panel<input name="label"></label><label>Español<textarea name="value_es"></textarea></label><label>English<textarea name="value_en"></textarea></label><label id="image-upload" hidden>Nueva imagen<input type="file" name="image" accept="image/jpeg,image/png,image/webp,image/avif"></label><button>Guardar y actualizar vista</button><p class="save-state" role="status"></p></form><div id="product-inspector" class="product-inspector" hidden><p class="admin-eyebrow">Ficha de producto</p><h2>Información estructurada</h2><p>Este bloque se administra desde una sola ficha para conservar especificaciones, empaques y calendario.</p><a id="product-edit-link" class="product-edit-link">Editar ficha del producto</a></div></aside></section></main><script>
const picker=document.querySelector('#page-picker'),frame=document.querySelector('#preview'),form=document.querySelector('#field-form'),empty=document.querySelector('#empty'),productBox=document.querySelector('#product-inspector'),publicLink=document.querySelector('#public-link');let selected=null;
function current(){const option=picker.selectedOptions[0];return{url:option.value,page:option.dataset.page,lang:option.textContent.includes('English')?'en':'es'}}
function loadPage(){const item=current();frame.src=item.url+(item.url.includes('?')?'&':'?')+'cms_preview=1';publicLink.href=item.url;form.hidden=true;productBox.hidden=true;empty.hidden=false}
picker.addEventListener('change',loadPage);document.querySelectorAll('[data-device]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-device]').forEach(x=>x.classList.remove('active'));button.classList.add('active');frame.className='preview-frame '+(button.dataset.device==='monitor'?'':button.dataset.device)}));
frame.addEventListener('load',()=>{const doc=frame.contentDocument;if(!doc)return;const style=doc.createElement('style');style.textContent='[data-cms],[data-product-id]{cursor:pointer!important;outline:1px dashed transparent;outline-offset:4px;transition:outline-color .2s,box-shadow .2s}[data-cms]:hover,[data-product-id]:hover{outline-color:#79b855!important;box-shadow:0 0 0 5px #c6ee9b33!important}';doc.head.append(style);doc.querySelectorAll('[data-cms],[data-product-id]').forEach(el=>el.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();if(el.dataset.productId){showProduct(el.dataset.productId);return}showField(el.dataset.cms,el)}))});
async function showField(key,element){selected=element;empty.hidden=true;productBox.hidden=true;form.hidden=false;const item=current(),response=await fetch('/admin/editor-api.php?page='+encodeURIComponent(item.page)+'&key='+encodeURIComponent(key)),payload=await response.json(),field=payload.field;form.page_key.value=item.page;form.key.value=key;form.editing_lang.value=item.lang;form.field_type.value=field.field_type||((element.tagName==='IMG')?'image':'text');form.label.value=field.label||key;form.value_es.value=field.value_es||element.textContent.trim();form.value_en.value=field.value_en||'';document.querySelector('#field-name').textContent=field.label||key;document.querySelector('#image-upload').hidden=form.field_type.value!=='image'}
function showProduct(id){empty.hidden=true;form.hidden=true;productBox.hidden=false;document.querySelector('#product-edit-link').href='/admin/product-details.php?id='+id}
form.field_type.addEventListener('change',()=>document.querySelector('#image-upload').hidden=form.field_type.value!=='image');form.addEventListener('submit',async event=>{event.preventDefault();const state=form.querySelector('.save-state');state.textContent='Guardando…';const response=await fetch('/admin/editor-api.php',{method:'POST',body:new FormData(form)}),payload=await response.json();if(!response.ok){state.textContent=payload.error||'No se pudo guardar';return}const lang=current().lang,value=payload[lang==='en'?'value_en':'value_es'];if(selected&&value){if(payload.type==='image')selected.src=value;else if(payload.type==='url')selected.href=value;else selected.textContent=value}state.textContent='Cambios guardados';setTimeout(()=>state.textContent='',1800)});
</script></body></html>
